name: CI/CD Spring Boot & Docker

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Spring Boot Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Young_Hana Securyity Copy 
        run: cp /home/Young_Hana-Security/BackEnd/application.properties ./ && cp /home/Young_Hana-Security/BackEnd/db1-config.xml ./src/main/resources/mapper/db1/
