name: CI/CD Spring Boot & Docker

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Spring Boot Project
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Version
        run: export VERSION=$(date +%y.%m.%d)
      - name: Young_Hana Securyity File Copy 
        run: cp /drive/Young_Hana-Security/BackEnd/application.properties ./ ; cp /drive/Young_Hana-Security/BackEnd/db1-config.xml ./src/main/resources/mapper/db1/ ;
      - name: Spring Boot Maven Build
        run: mvn clean package -Dmaven.test.skip=true
      - name: Docker Image Build
        run: docker build -t younghnan_backend .
      - name: Docker Image Stop/Start
        run: docker stop younghnan_backend ; docker rm younghnan_backend ; docker run -d --name younghnan_backend -p 80:8080 younghnan_backend ;
