name: CI/CD Spring Boot & Docker

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Spring Boot Project
    runs-on: CentOS 7

    steps:
      - uses: actions/checkout@v3
      - run: pwd
