name: CI/CD Spring Boot & Docker

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Spring Boot Project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: echo Start
      - run: pwd
      - run: ls -la
