name: CI/CD Spring Boot & Docker

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Spring Boot Project
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3
      - name: Young_Hana Securyity File Copy 
        run: cp /drive/Young_Hana-Security/BackEnd/application.properties ./ && cp /drive/Young_Hana-Security/BackEnd/db1-config.xml ./src/main/resources/mapper/db1/
      - name: Spring Boot Maven Build
        run: mvn clean package -Dmaven.test.skip=true
